//
// Created by Maxwell Murphy on 11/25/19.
//

#ifndef TRANSMISSION_NETWORKS_APP_LIKELIHOODFUNCTIONPARAMETERS_H
#define TRANSMISSION_NETWORKS_APP_LIKELIHOODFUNCTIONPARAMETERS_H


class LikelihoodFunctionParameters {

};


#endif //TRANSMISSION_NETWORKS_APP_LIKELIHOODFUNCTIONPARAMETERS_H
