//
// Created by Maxwell Murphy on 2/6/20.
//

#ifndef TRANSMISSION_NETWORKS_APP_TRANSMISSIONPROCESSLIKELIHOOD_H
#define TRANSMISSION_NETWORKS_APP_TRANSMISSIONPROCESSLIKELIHOOD_H


template <int MAX_COI>
class TransmissionProcessLikelihood {
public:

};



#endif //TRANSMISSION_NETWORKS_APP_TRANSMISSIONPROCESSLIKELIHOOD_H
