//
// Created by Maxwell Murphy on 2/26/20.
//

#ifndef TRANSMISSION_NETWORKS_APP_PROBABILITYVECTOR_H
#define TRANSMISSION_NETWORKS_APP_PROBABILITYVECTOR_H

using ProbabilityVector = std::vector<double>;

#endif //TRANSMISSION_NETWORKS_APP_PROBABILITYVECTOR_H
