//
// Created by Maxwell Murphy on 10/25/19.
//

#ifndef TRANSMISSION_NETWORKS_TRANSMISSIONNETWORKMODEL_H
#define TRANSMISSION_NETWORKS_TRANSMISSIONNETWORKMODEL_H


class TransmissionNetworkModel {

};


#endif //TRANSMISSION_NETWORKS_TRANSMISSIONNETWORKMODEL_H
