//
// Created by Maxwell Murphy on 12/2/21.
//

#ifndef TRANSMISSION_NETWORKS_APP_SAMPLERLOGGER_H
#define TRANSMISSION_NETWORKS_APP_SAMPLERLOGGER_H


class SamplerLogger {
};


#endif//TRANSMISSION_NETWORKS_APP_SAMPLERLOGGER_H
