#ifndef TRANSMISSION_NETWORK_MODEL_TRANSMISSIONNETWORKMODELCONFIG_H
#define TRANSMISSION_NETWORK_MODEL_TRANSMISSIONNETWORKMODELCONFIG_H

constexpr int MAX_ALLELES = 32;
constexpr int MAX_COI = 20;
constexpr int MAX_TRANSMISSIONS = 10;

#endif //TRANSMISSION_NETWORK_MODEL_TRANSMISSIONNETWORKMODELCONFIG_H
